version: '3.1'

services:
 nextcloud:
    image: nextcloud
    restart: always
    container_name: test_nextcloud
    environment:
        SQLITE_DATABASE: nextcloud
        NEXTCLOUD_ADMIN_USER: ${NC_TEST_ADMIN_NAME}
        NEXTCLOUD_ADMIN_PASSWORD: ${NC_TEST_ADMIN_PWD}
    ports:
        - "8080:80"

 sftp:
    image: onescript-ssh/test-ssh
    build:
        context: "./openssh"
        args:
            SSH_TEST_USER: ${SFTP_TEST_USER}
            SSH_TEST_PWD: ${SFTP_TEST_PWD}
    container_name: test_ssh
    ports:
        - "2222:22"
